[Feat] PostView 페이지 구현 (API 연동)
Team-SilverTown/Team-SilverTown-MasilGasil-FE pull request #190
Opened 2024-03-12 01:21 UTC by SeungHyune

## 🔗 이슈 링크

- #177 

## 💡 핵심 구현 사항

https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/114329713/ea9a1b4e-4293-4d33-91b3-ce77448fd272

- **API 연동** (메이트쪽은 현재 API가 완료되지 않아 Response 데이터를 통해 산책 메이트 리스트를 만들었습니다.)
- **지도 구현**
- 지도는 산책 path의 중심 좌표를 계산하여 중심 위치를 잡습니다.
- 지도 하단에 있는 아이콘을 클릭 시 처음에 계산 한 `baseLocation` 값으로 이동합니다.
- 지도에 표시된 핀을 누르면 핀 탭으로 이동되는 동시에 해당 핀 번호 케러셀 위치로 이동 됩니다.
- 
- **메모 탭 구현**
  - `PostData`를 통해 **메모 페이지를 구현** 했습니다.
  - **산책하기 버튼**을 누르면 해당 **`/log/record?postId=id값`으로 이동** 되어 `log/record` 페이지에서는 해당 post 데이터를 불러와 post 산책로를 산책할 수 있습니다.
- **핀 탭 구현**
  - **핀 탭으로 이동 시 지도의 중심 위치가 1번 핀 위치로 이동**되도록 구현 했습니다.
  - 핀 탭으로 **케러셀 움직일 수 있으며 이동 시 핀 번호에 맞게 지도의 중심 위치가 이동** 됩니다.
- **산책 메이트 탭 구현**
  - 현재 Post View를 통한 산책 메이트 모집 리스트를 보여줍니다.
  - **산책 메이트 모집 리스트**를 클릭하면 해당 **`/mate/:mateid`로 이동**됩니다.
  - **메이트 모집하기** 버튼을 누르면 **`/mate/create?lat=lat&lng=lng`**으로 이동 됩니다. (메이트 모집하기 페이지에 현재 **산책로의 시작 path 값을 쿼리 스트링으로 전달**합니다.)

## ➕ 추가 작업 사항

- `PinDetailCard` 컴포넌트에 **thumbnail 이미지가 null이 들어갔을 때 배경 이미지 배경색이 회색으로 표시되도록 style 추가**했습니다.

## 🤔 테스트 및 검증 && 고민 사항

- 

## 💬 피드백 반영사항

-

2024-03-12 02:38 UTC, Jae0o approved these changes
수고하셨습니다!

2024-03-12 02:38 UTC, Jae0o commented on src/app/mate/[id]/components/MateInfo/components/MateDropDownMenu/MateDropDownMenu.tsx
> +                  {" "}
[ P5 ] 요거 지워주실 수 있으실까요?!

2024-03-12 02:38 UTC, Jae0o commented on src/app/mate/[id]/components/MateInfo/components/MateDropDownMenu/MateDropDownMenu.tsx
[ P2 ] 
요기가 변경되면서 현재 mate Detail 페이지의 DropDown 내부의 버튼이 동작안하더라구요! 

그리고 다른곳에서도 사용되는 만큼 `MateDropDownMenu`가 아닌 `DropDownMenu` 라는 이름으로 공용컴포넌트로 분리되는게 좋을것같아요!

2024-03-12 02:38 UTC, Jae0o commented on src/app/log/[id]/Log.view.tsx
> +import { userInfo } from "os";
[ P5 ] 현재 요 Info는 사용이 안되고 있는것 같습니다!

2024-03-12 04:56 UTC, OhWonJu approved these changes
고생하셨습니다

2024-03-12 04:56 UTC, OhWonJu commented on src/app/post/[id]/Post.controller.tsx
> +  const handlePinIndex = (PinIndex: number) => {
아니면 handleCurrentPinIndex 도 좋아 보이네요

2024-03-12 15:15 UTC, w00ngja approved these changes
고생 많으셨습니다 승현님! 작업량이....굉장하네요..🥹 log view랑 post view 합치는 것도 너무 좋을 것 같습니다!

2024-03-12 15:15 UTC, w00ngja commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +    <>
container 좌우 패딩이 다른 것 같은데 확인 한 번만 해주시면 감사드리겠습니다~! 또 좌우 패딩값 자체를 조금 더 좋을 것 같다는 생각입니다.

2024-03-12 15:15 UTC, w00ngja commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +        진주시에서 가장 큰 강이 남강변을 따라 걷는 산책로에요. 주변을 걷다보면 수달을 만날 수도
[ ASK ]

요 부분은 아직 API 작업이 안 된건가요?

2024-03-12 15:15 UTC, w00ngja commented on src/app/log/[id]/components/LogPin/LogPin.tsx
> +          <Carousel
[ P5 ]

아이폰에서 캐러셀 아래가 잘리는 것 같더라고요..? 지도가 작아지더라도 화면에 캐러셀이 전부 보여지는게 좋을 듯 한데.. 배포하고 한 번 확인해보면 좋을 것 같습니다~~

2024-03-12 15:15 UTC, w00ngja commented on src/app/post/[id]/Post.view.tsx
> +            {tabIndex === PostTabType.Mate && <PostMate mateData={mateData} />}
MateItem 좌우 그림자가 잘리는 듯한..? 현상이 있는 것 같습니다! 확인 한 번 해주시면 좋을 것 같습니돠🤗

2024-03-12 15:49 UTC, SeungHyune commented on src/app/post/[id]/Post.view.tsx
좋은 의견이십니다 감사합니다 !! 👍👍

2024-03-12 15:50 UTC, SeungHyune commented on src/app/post/[id]/Post.view.tsx
아이고.. 이 부분 확인하지 못하고 못지웠는데 확인 감사합니다 !! 😊

2024-03-12 15:51 UTC, SeungHyune commented on src/app/post/[id]/Post.controller.tsx
> +  if (!postData) {
[ ASK ]
그럼 로딩 중 일 때 처리는 어떤 UI를 보여주면 될까요 ??!

2024-03-12 15:52 UTC, SeungHyune commented on src/app/post/[id]/Post.controller.tsx
> +  const handlePinIndex = (PinIndex: number) => {
좋은 의견들 감사합니다 !!

`handleCurrentPinIndex `로 통일 시켜 놓겠습니다 !! 😇

2024-03-12 15:54 UTC, SeungHyune commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +        진주시에서 가장 큰 강이 남강변을 따라 걷는 산책로에요. 주변을 걷다보면 수달을 만날 수도
아하! 현재 LogView 페이지 UI 작업 완료하고 해당 브랜치를 머지 하여 사용하다 보니.. 헷갈리셨을 겁니다 ㅠㅠ

PostView 페이지만 봐주시면 될 것 같습니다 !! (해당 페이지는 따로 PR 올려뒀습니다😊 )

2024-03-12 16:34 UTC, SeungHyune commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +    <>
혹시 피그마 레이아웃처럼 현재 15px로 되어 있는 좌우 패딩을 20px 수정 해달라는 말씀이실 가까요 ?!! 👀

일단 20px로 수정하고 답 주시면 다시 수정하도록 하겠습니다 ~~!! 😊

2024-03-12 16:46 UTC, SeungHyune commented on src/app/log/[id]/components/LogPin/LogPin.tsx
> +          <Carousel
지도의 높이를 45%로 조정하니깐 잘 보이는 것 같네요 !! 🥳
혹시라도 잘 안 보이시면 말씀해주세요 ~~ㅎㅎ 😇

2024-03-13 00:52 UTC, Jae0o commented on src/app/post/[id]/Post.controller.tsx
> +  if (!postData) {
로딩중에는 그냥 지금처럼 보여져도 될것같은데 오히려 데이터가 정상적으로 불려오지 못했을때를 생각해보면좋을것같네요!

not-found로 내보낸다던지

```
if( !isLoading && !postData ){

 // 별도 처리

}
```

2024-03-13 01:28 UTC, w00ngja commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +    <>
<img width="242" alt="스크린샷 2024-03-13 오전 10 22 05" src="https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/95916813/07c2f0b0-8c64-4937-8155-9794074ecc26">

옆에가 너무 가까운 것 같아 말씀 드렸었는데, 녹화하시면서 잘린 것 같기도 하네요!

모바일에서는 좌우 패딩이 너무 답답해보이긴 하더라고요..! 20px이나 15px로 설정하고 배포 후 확인해봐도 좋을 것 같습니다 🙂

2024-03-13 01:40 UTC, OhWonJu reviewed
고생하셨습니다~~~
POST 데이터는 서버사이드에서 패치받아 클라이언트 사이드로 내려주는 것이 좋을 것 같습니다.
아무래도 Post 는 SEO 에 걸리도록 하는게 좋을 것 같네요!

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/Post.controller.tsx
> +  if (!postData) {
스켈레톤 ui 를 보여주면 좋을 것 같네요

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/Post.model.ts
> +  });
[ P1 ]
포스터의 경우 SEO 를 신경 쓰는게 좋을 것 같습니다. 이를 위해서 서버사이드 fetch 를 통해서 postdata 를 받아오고 view 로 내려주는 것이 좋아 보입니다.

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/Post.view.tsx
> +
Suspense 를 사용하려면 이부분에서 서버사이드 데이터를 패치받아야할 것 같네요.

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/Post.controller.tsx
> +};
[ P1 ]
포스터 데이터를 서버사이드에서 내려받게 되면
```
<Suspense fallback={<SomeSkeleton />}>
 <PostView />
</Suspense>
```
이런식으로 UI 를 불러 올 수 있을 것 같습니다.


이를 위해서 두가지 방법을 고려할 수 있을 것 같은데요.
1. view 내부에서 서버사이드 데이터 패칭 -> SEO meta 도 View 에서 지정..(페이지 명칭을 해치게 됨)
2. pages.tsx 에서 서버사이드 데이터 패칭 -> Controller 에 props 로 내려줌 
   - 이 경우 Suspense 를 사용할 수 없을 것으로 보이네요. if 문을 통해서 data 여부에 따라 스켈레톤 UI 를 보여주어야 함..
   - pages 에서 SEO 를 작성할 수 있게 될 것으로 보임.
   - 그리고 Suspens 를 Controller 에서 쓸 수 없을 것으로 보입니다.

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/components/PostMapSection/PostMapSection.tsx
> +import { PostDetailResponse } from "@/types/Response/Post";
[ P5 ]
Log PR 에 남긴 의견처럼 이부분도 Section 과 component 디렉토리를 분리하는 것이 좋아보입니다!

2024-03-13 01:40 UTC, OhWonJu commented on src/app/post/[id]/components/PostMateCard/PostMateCard.styles.ts
> +import { FONT_SIZE, FONT_WEIGHT } from "@/styles/theme";
[ P1 ]
PostMateCard 도 공용 컴포넌트로 분리해야할 것 같습니다.
탐색 페이지에서도 사용될 예정입니다..!

2024-03-13 01:42 UTC, OhWonJu requested changes
.

2024-03-13 09:05 UTC, Songhee99 approved these changes
승현님 고생 많으셨습니다 !!
저도 API 연결할 때 코드 참고하면서 많이 배우겠습니다 ㅎㅎ 👍🏻

2024-03-13 13:39 UTC, SeungHyune commented on src/app/log/[id]/components/LogMemo/LogMemo.tsx
> +    <>
넵 ㅎㅎ 기본 20px 지정하고 내부 컨텐츠 5px 정도 여유 공간 주겠습니다 ㅎㅎ 😊

2024-03-13 13:46 UTC, SeungHyune commented on src/app/post/[id]/Post.controller.tsx
> +  if (!postData) {
서버 데이터 패칭으로 변경하였습니다 !! 😇
스켈레톤 Ui는 추후에 `PostView`, `LogView`에 추가하여 다시 PR 날리도록 하겠습니다 !!

2024-03-13 13:49 UTC, SeungHyune commented on src/app/post/[id]/Post.controller.tsx
> +};
2번 사항으로 처리했습니다!!
스켈레톤 UI는 선 merge 후 추가 PR을 통해 추가하도록 하겠습니다!! 😊

2024-03-13 13:50 UTC, SeungHyune commented on src/app/post/[id]/components/PostMapSection/PostMapSection.tsx
> +import { PostDetailResponse } from "@/types/Response/Post";
넵 ㅎㅎ `log`, `post` 모두 수정하도록 하겠습니다 !! 👍👍

2024-03-13 13:52 UTC, SeungHyune commented on src/app/post/[id]/components/PostMateCard/PostMateCard.styles.ts
> +import { FONT_SIZE, FONT_WEIGHT } from "@/styles/theme";
공용 컴포넌트로 이동 시켜놓겠습니다 !! 🥳

2024-03-14 01:03 UTC, OhWonJu approved these changes
고생하셨습니다

2024-03-14 02:09 UTC, merged