[Feature] LogDetailCard 컴포넌트 생성 / #19
Team-SilverTown/Team-SilverTown-MasilGasil-FE pull request #32
Opened 2024-02-14 18:46 UTC by SeungHyune

## 🔗 이슈 링크

- #19 

## 💡 핵심 구현 사항

- 제목 및 간단한 메모를 보여준다.
- 토글 버튼을 누르면 삭제하기, 수정하기 버튼이 나타난다.
- 하단에는 산책에 관한 정보를 보여준다.(산책 시간, 산책 거리, 운동 칼로리 소모)

## ➕ 추가 작업 사항

- LogDetailCard 컴포넌트 storybook 등록해 놓았습니다. (UI로 확인해 주시면 감사드리겠습니다.)

## 🤔 테스트 및 검증 && 고민 사항

- `LogDetailCardSettingModal` 컴포넌트는 따로 분리하는 게 좋을지 궁금합니다.
- px 단위를 모두 rem으로 수정하였는데 모두 변경하는 것이 좋을지 궁금합니다.
  - ex ) `box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px`, `calc(100% - 10px)`

## 💬 피드백 반영사항

-

2024-02-15 00:32 UTC, OhWonJu requested changes
고생하셨습니다. 몇가지 수정 사항이 있는 것 같아요.

2024-02-15 00:32 UTC, OhWonJu commented on src/components/LogDetailCard/index.tsx
> +              <div className="like">{like_cnt < 999 ? like_cnt : "+999"}</div>
[ P2 ]
컨벤션 룰에 따르면 like_cnt 보다는 likeCount 로 해주시는게 좋을 것 같아요!

2024-02-15 00:32 UTC, OhWonJu commented on src/components/LogDetailCard/index.tsx
> +          </LogDetailCardSettingModal>
[ P2 ] 
모달을 사용하는 경우라면 기존에 구현된 모달 컴포넌트를 사용하는게 좋을 것 같습니다!

2024-02-15 00:34 UTC, OhWonJu commented on src/components/LogDetailCard/index.tsx
> +          </LogDetailCardSettingModal>
스토리북으로 확인해보니까, dropdown 의 성향이 크네요.
음...일단은 이대로 진행하고 추후에 doropdown 컴포넌트를 추가적으로 구현하는게 좋을 것 같아보이네요.

2024-02-15 01:11 UTC, SeungHyune commented on src/components/LogDetailCard/index.tsx
> +              <div className="like">{like_cnt < 999 ? like_cnt : "+999"}</div>
아아.. 제가 놓쳤네요.. ㅠㅠ 감사합니다 !!
명세서 보고 그대로 작성했는데 수정해놓겠습니다 !! 😊

2024-02-15 02:04 UTC, SeungHyune commented on src/components/LogDetailCard/index.tsx
> +          </LogDetailCardSettingModal>
아아.. 임시로 넣어놓은 거긴 했는데 dropdown 모달 컴포넌트를 공통으로 따로 만들어 놓을까요 ?!

2024-02-15 03:12 UTC, Songhee99 approved these changes
승현님 로그 디테일 카드 구현하시느라 고생 많으셨습니다 !! 👍🏻

2024-02-15 03:12 UTC, Songhee99 commented on src/stories/LogDetailCard.stories.tsx
> +  content: "집 앞 강변을 따라 걷는데 너무 좋은거에요 그래서 이러쿵저러쿵이러쿵 저러쿵 공유해봅니다",
content 내용이 너무 귀엽네요 ㅎㅎ 😆

2024-02-15 03:45 UTC, w00ngja approved these changes
추후 드롭다운 컴포넌트 공통으로 빼고, 하드 바인딩된 데이터 로직 구현되면 붙혀주면 될 것 같네요! 고생하셨습니다 승현님 👍🏻

2024-02-15 04:19 UTC, Jae0o approved these changes

2024-02-15 04:19 UTC, Jae0o commented on src/components/LogDetailCard/LogDetailCard.style.ts
> +      font-size: 1.6rem;
```suggestion
      width: ${(props) => (props.isSettingLayout ? "calc(100% - 1.5rem)" : "100%")};
      font-size: 1.6rem;
```

[ P4 ] 요러면 오떨까요!

2024-02-15 04:19 UTC, Jae0o commented on src/components/LogDetailCard/LogDetailCard.style.ts
> +      -webkit-box-orient: vertical;
```suggestion
      white-space: nowrap;
     text-overflow : text-overflow: ellipsis;
```

[ P999 ] 여기는 한줄이라 위와 같이 처리할 수도 있을 것 같은데
 webkit 말고 요렇게는 적용하면 예상과 다르게 동작하실까요?!

2024-02-15 07:02 UTC, SeungHyune commented on src/components/LogDetailCard/LogDetailCard.style.ts
> +      font-size: 1.6rem;
`calc(), box-shadow` 정의 부분들도 싹 `rem` 단위로 변경해야겠네요 !! 감사합니다 ㅎㅎ 👍👍

2024-02-15 07:19 UTC, SeungHyune commented on src/components/LogDetailCard/LogDetailCard.style.ts
> +      -webkit-box-orient: vertical;
좋은 말씀이십니다 !
한 줄은 재영님이 말씀해 주신 코드로도 정상 동작할 것 같네요 !!
습관적으로 적어버렸네요..! ㅎㅎ 😂 

(일반 css 속성과 webkit css 속성의 차이에 대해서 알아보니 **브라우저 호환성 측면에서 webkit은 정말 필요할 때만 사용**하는 것이 좋다고 하네요..! 수정하겠습니다 감사합니다 ㅎㅎ)

2024-02-16 04:14 UTC, OhWonJu approved these changes

2024-02-16 04:44 UTC, merged