[Feat] Bottom 네비게이터 구현
Team-SilverTown/Team-SilverTown-MasilGasil-FE pull request #35
Opened 2024-02-15 01:12 UTC by Songhee99

## 🔗 이슈 링크
- #8  

## 💡 핵심 구현 사항
- 하단 네비게이터 구현
- 해당 페이지 접속시 아이콘 색상 및 모양 변경

## ➕ 추가 작업 사항

## 🤔 테스트 및 검증 && 고민 사항
- 마이페이지 경로 활성 상태를 계속 true로 두고, 현재 경로와 비교해서 마이페이지에 접속하면 색상이 바뀌도록 해두었습니다.
아이콘 색깔만 바뀌는 거라 상태관리까지는 굳이 싶은가 해서용 ..!
- 내 기록, 마이페이지의 path 경로는 임의로 설정해두었습니당

## 💬 피드백 반영사항

2024-02-15 02:45 UTC, SeungHyune requested changes
송희님 고생 많으셨습니다 !! 😊
깔끔하게 잘 짜주신 것 같습니다 !! 👍👍
(Style 적으로만 조그마한 코맨트 남겨드립니다 !)

2024-02-15 02:45 UTC, SeungHyune commented on src/components/BottomNavBar/BottomNavBar.style.ts
> +export const BottomNavContainer = styled.div`
[ P1 ]
`BottomNavContainer `에 `z-index` 값을 지정해주면 좋을 것 같습니다 !! 😇

2024-02-15 02:45 UTC, SeungHyune commented on src/components/BottomNavBar/BottomNavBar.tsx
> +        >
[ P5 ]
`<Link>` 태그에 `title={label}` 속성 추가해 주시는 건 어떨까요 ?!
조심스럽게 제안 드립니다 ! 😊

2024-02-15 02:45 UTC, SeungHyune commented on src/components/BottomNavBar/BottomNavBar.style.ts
> +export const BottomNavItem = styled.div<{ active: boolean }>`
[ P5 ]
모바일 환경이라 상관없을 수도 있겠지만 **Mouse Hover 시에 svg, 글자 색 변경해 줘도 좋을 것 같습니다 !!** 😊

2024-02-15 03:13 UTC, Songhee99 commented on src/components/BottomNavBar/BottomNavBar.style.ts
> +export const BottomNavContainer = styled.div`
넵 !! 반영해두겠습니다 ㅎㅎ

2024-02-15 03:13 UTC, Songhee99 commented on src/components/BottomNavBar/BottomNavBar.tsx
> +        >
오오 좋은 제안입니다 !! 추가해두겠습니당~

2024-02-15 03:13 UTC, Songhee99 commented on src/components/BottomNavBar/BottomNavBar.style.ts
> +export const BottomNavItem = styled.div<{ active: boolean }>`
헉 그러면 센스있겠네요 !! 이것도 추가해두겠습니다 👍🏻

2024-02-15 07:21 UTC, SeungHyune approved these changes

2024-02-15 14:44 UTC, Jae0o approved these changes
수고하셨습니다 멘탈 케어 담당자님 🙋‍♂️

2024-02-15 14:44 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.style.ts
> +  background-color: ${(props: any) => props.theme.container_color};
[ P3 ]

```suggestion
  background-color: ${({theme}) => theme.container_color};
```
요렇게 변경하실 수 있을것 같습니다!

2024-02-15 14:44 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.style.ts
> +export const BottomNavItem = styled.div<{ active: boolean }>`
[ P2 ] 보통 styled components 사용할때 prop이 있다면 prop의 이름 앞에 `$`를 붙여주더라구요!
실제로 지난번 프로젝트때 저도 안붙여줬을때 에러가 생기는 경우도 많았어서 붙이시면 좋을 것같습니다!

```suggestion
export const BottomNavItem = styled.div<{ $active: boolean }>`
```

2024-02-15 14:44 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +  ];
[ P3 ] 요 친구가 어쩌면 상수처럼 보이는 면도 있어서 별도로 상수처럼 관리해주셔더 좋을것 같습니다!

2024-02-15 14:44 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +    { path: "/user/id/diary", icon: <Diary />, activeIcon: <DiaryFill />, label: "내 기록" },
[ ASK ] 혹시 path 경로에서 저렇게 id 라고 해주면 정상적으로 라우트가 인식하나요?! 그러하다면 처음봐서 신기하네요 🤔

2024-02-15 14:44 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +            )}
[ P3 ] 개인적으로는 삼항 연산자가 2번 연속으로 쓰이면 읽기가 많이 들더라구요.. 🤦
그래서 저는 보통 이런경우 요렇게 사용하는편이라 한번 의견 드려봅니다
 
```suggestion
{ isProfile && <S.ProfileCircle active={isPathActive(path)} /> }

{ !isProfile && isPathActive(path) ? activeIcon : icon }
```

2024-02-15 14:46 UTC, Jae0o approved these changes

2024-02-15 14:46 UTC, Jae0o commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +  activeIcon?: JSX.Element;
[ P3 ] 제가 테스트할 수 있는 환경이 안돼서 정상 동작할지 모르겠지만 ㅠ  된다면! 
아래 처럼 수정해 주신다면 컨벤션에도 잘 맞을것 같아요!  

```suggestion
  icon?: React.ReactNode;
  activeIcon?: React.ReactNode;
```

2024-02-15 14:56 UTC, w00ngja commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +            )}
엇 이거 제가 알기론 린트에서도 잡아주는 걸로 알고 있는데..! 송희님 혹시 따로 Caution은 발생하지 않으셨나요? 👀

2024-02-15 14:59 UTC, w00ngja approved these changes
고생하셨습니다 송희님~! 아이콘 크기가 24px인가요? 개인적으로 버튼들 쪼~끔만 더 커도 좋을 것 같다는 생각입니다. 다른 분들 의견도 궁금하네요..!

2024-02-15 16:25 UTC, Songhee99 commented on src/components/navigators/BottomNavigator/BottomNavigator.style.ts
> +export const BottomNavItem = styled.div<{ active: boolean }>`
오! 스타일링을 위한 props를 구분하면 진짜 좋겠네요 ㅎㅎ 에러 방지를 위해서라도 꼭 붙이겠습니다~!!

2024-02-15 16:28 UTC, Songhee99 commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +    { path: "/user/id/diary", icon: <Diary />, activeIcon: <DiaryFill />, label: "내 기록" },
네네! id라고 써줘야 인식하더라구요~ㅎㅎ

2024-02-15 18:41 UTC, SeungHyune commented on src/components/navigators/BottomNavigator/BottomNavigator.style.ts
> +export const BottomNavItem = styled.div<{ active: boolean }>`
저도 통일 시키는 게 좋겠네요..! 👍

2024-02-16 02:06 UTC, OhWonJu commented on src/components/navigators/BottomNavigator/BottomNavigator.tsx
> +    { path: "/user/id/diary", icon: <Diary />, activeIcon: <DiaryFill />, label: "내 기록" },
[ P4 ]
추후에 로그인 되어서 전역 상태에 id 값이 존재하게 되면

path: `/user/{id}/diary` 형태로 변경해야할 겁니다!

2024-02-16 06:18 UTC, merged