[Feat] LogRecord Step2 Finally
Team-SilverTown/Team-SilverTown-MasilGasil-FE pull request #52
Opened 2024-02-17 13:39 UTC by Jae0o

## 🔗 이슈 링크

- #15 
close #15  

![image](https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/127748428/83e02895-b6ce-40c0-baeb-ecf2a1093647)

![image](https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/127748428/3f415550-4edd-432e-8719-1700d3510587)

## 💡 핵심 구현 사항

- 모든 에러에 대해 Alert 모달을 적용

- 기존 Pin 추가 방식
  - 특정 M 이내에 Pin이 존재하면 찍히지 않도록 개선

- Path 추가 방식을
  - 기존 throttle 방식으로 5초에 한번 동작하도록 구현
  - 추가로 setter 동작 이전 거리와 비교하여 path를 추가할지에대한 조건 추가

## ➕ 추가 작업 사항

- 기존 Confirm Modal을 재사용성있게 개선하여 하나의 Confirm 모달로 통일
- Alert Modal을 구현 

## 🤔 테스트 및 검증 && 고민 사항

- 

## 💬 피드백 반영사항

-

2024-02-18 01:12 UTC, OhWonJu requested changes
고생하셨습니다~~!

2024-02-18 01:12 UTC, OhWonJu commented on src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
[ P5 ]
func 보단 utiles 디렉토리에 위치시키는게 좋아보이네요!

2024-02-18 01:12 UTC, OhWonJu commented on src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
>        });
[ P4 ] 
set 함수 내부보다는
외부에서 if(!getTowPointDistance === 조건 만족) return 
set(....)

형태로 얼리리턴하는 방식이 좋아보입니다.

2024-02-18 01:12 UTC, OhWonJu commented on src/components/uiContext/types/modalType.ts
> +export type MODAL_VIEWS = "INIT_VIEW" | "CONFIRM" | "ALERT";
[ P2 ] 
MODAL_VIEWS 형식을 맞추기 위해 CONFIRM_VIEW ,ALERT_VIEW 라고 맞추는개 좋을 것 같습니다~

2024-02-18 01:53 UTC, Jae0o commented on src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
오홓 좋습니다! 바로 수정하겠습니다

2024-02-18 01:54 UTC, Jae0o commented on src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
>        });
이게 현재  useRef를 통해서 throttle이 동작될 수 있도록 하다보니 setter내부가 아니면 logData에 존재하는 path가 useRef정의 당시 빈배열 그대로 남아있어서 setter내부가 아니면 동작을 하지 않습니다 ㅠㅠ

2024-02-18 01:56 UTC, Jae0o commented on src/components/uiContext/types/modalType.ts
> +export type MODAL_VIEWS = "INIT_VIEW" | "CONFIRM" | "ALERT";
오호 그리고 추가로 여쭤보고싶은게 현재 제작한 Modal을 Log Record페이지 내부에서만 사용하게 된다면 LOG_CONFIRM_VIEW 같은 형태가 맞을것 같은데 

전역으로 사용되도록 이름을 놔둘까요? 혹은 Log Record 페이지에서만 사용되도록 네이밍을 할까요?

2024-02-18 03:52 UTC, OhWonJu commented on src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
>        });
그렇군요.. ! 확인했습니다!

2024-02-18 03:53 UTC, OhWonJu commented on src/components/uiContext/types/modalType.ts
> +export type MODAL_VIEWS = "INIT_VIEW" | "CONFIRM" | "ALERT";
그렇다면 변경하는게 좋지 않을까요?!

2024-02-19 01:18 UTC, OhWonJu approved these changes

2024-02-19 01:27 UTC, OhWonJu approved these changes

2024-02-19 01:43 UTC, Songhee99 approved these changes
재영님 고생하셨습니다 👍🏻

2024-02-19 02:02 UTC, SeungHyune approved these changes
재영님 고생 많으셨습니다 !! 😊

2024-02-19 02:02 UTC, SeungHyune commented on src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
> +          <Button
[ P5 ]
버튼의 `width` 값을 조금 더 키워 간격을 줄여도 괜찮을 것 같습니다 !! 😊

2024-02-19 03:09 UTC, merged

2024-02-19 03:10 UTC, Jae0o commented on src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
> +          <Button
그렇다면 살짝 키워보겠습니다!